import { GlobalContextProvider } from '@/context/store';
import './globals.css';
import { Poppins } from 'next/font/google';
import { Suspense } from 'react';
import { Toaster } from 'react-hot-toast';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: 'YukUMKM',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/assets/img/logo/logo1.png" sizes="any" />
      <body className={`${poppins.variable} ${poppins.className}`}>
        <div className="loader">
          <div></div>
        </div>
        <Toaster position="top-center" />
        <Suspense
          fallback={
            <div className="text-center text-[32px] text-bluePallete-800">
              Loading...
            </div>
          }
        >
          <GlobalContextProvider>{children}</GlobalContextProvider>
        </Suspense>
      </body>
    </html>
  );
}
